### ISSUE TITLE
Fail on MSVC 9.0

### ISSUE THREAD

**Issue by bjoernthiel** [aantron/better-enums#6]
The following does not compile with MSVC 9.0:

#include "stdafx.h"

#include "enum.h"

ENUM(immersion_medium, int, unknown = -1, oil = 0, water, dry, silicone, glycerol)

int _tmain(int argc, _TCHAR* argv[])
{
	immersion_medium::_from_integral( 0 ) ;

	return 0;
}

error LNK2019: unresolved external symbol...

A copy constructor seems to be missing.

**Comment by aantron** [comment]
Thanks, taking a look.

**Comment by aantron** [comment]
Try the version in the commit above. It resolves the problem on my test machine. Here is the [raw link to the updated `enum.h`](https://raw.githubusercontent.com/aantron/better-enums/vc2008-copy-ctor/enum.h). I'm also working on a follow-on branch that adds automated VC9 testing in AppVeyor (their VC9 build system has been slightly problematic for the project, fixing that).

**Comment by aantron** [comment]
I'm working on fixing a run-time error in the code generated by VC9. Will let you know when VC9 code passes all the tests.

**Comment by aantron** [comment]
Please try the last commit above at your leisure, and let me know if it resolves the problem :) It passes all tests, including on VC9 (CI services seem to be running slow today, but I have a superset of the CI compilers installed locally, and tested on all of them, including VC9, which I just installed).

**Comment by bjoernthiel** [comment]
That helps :)
